# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57839d6daa8cb5781337b78476b707b038e018a60570df44dee171dfb9054d6459d20c62071c30c8e539b04286493c75433226426be04d0f7123796c0dd6149d

test:
  secret_key_base: 9a3aea0e23b8ac58b12ba9e17aa5ff1efde31fa40b4350425320397953b67d87af58da34f8a2484b33d7eec7857e88bfbb60b5c4c98dae9a2edea03a89754f46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
